---
- name: Crear usuarios con contrase침a default
  hosts: all
  become: true

  vars_files:
    - ../vars/users.yml
    - ../vars/default_password.yml

  tasks:
    - name: Crear usuarios con contrase침a default
      user:
        name: "{{ item.name }}"
        comment: "{{ item.full_name }}"
        password: "{{ default_password }}"
        shell: /bin/bash
        state: present
        create_home: yes
      loop: "{{ users }}"

    - name: Forzar cambio de contrase침a al iniciar sesi칩n
      command: chage -d 0 {{ item.name }}
      loop: "{{ users }}"
