---
- name: Eliminar usuarios definidos en users_to_delete.yml
  hosts: all
  become: true

  vars_files:
    - ../vars/users_to_delete.yml

  tasks:
    - name: Eliminar usuarios del sistema
      user:
        name: "{{ item }}"
        state: absent
        remove: yes  # Elimina también el home directory y mail spool
      loop: "{{ users_to_delete }}"
